type TYPE_FLEX_CONTAINER_PROPS =
  | 'row'
  | 'row-reverse'
  | 'column'
  | 'column-reverse'
  | 'nowrap'
  | 'wrap'
  | 'wrap-reverse'
  | 'flex-start'
  | 'flex-end'
  | 'center'
  | 'space-around'
  | 'space-between'
  | 'space-evenly'
  | 'inherit'
  | 'initial'
  | 'revert'
  | 'unset'
  | 'stretch'
  | 'baseline'
  | 'auto'
  | 'start'
  | 'end'
  | 'left'
  | 'right'
  | 'cover'
  | 'contain'
  | 'repeat'
  | 'no-repeat';

type TYPE_VALUE_PROPS =
  | 'row'
  | 'row-reverse'
  | 'column'
  | 'column-reverse'
  | 'nowrap'
  | 'wrap'
  | 'wrap-reverse'
  | 'flex-start'
  | 'flex-end'
  | 'center'
  | 'space-around'
  | 'space-between'
  | 'space-evenly'
  | 'inherit'
  | 'initial'
  | 'revert'
  | 'unset'
  | 'stretch'
  | 'baseline'
  | 'auto'
  | 'start'
  | 'end'
  | 'left'
  | 'right'
  | 'cover'
  | 'contain'
  | 'repeat'
  | 'no-repeat';

export type TYPE_FLEX = {
  $direction?: TYPE_FLEX_CONTAINER_PROPS;
  $alignSelf?: TYPE_FLEX_CONTAINER_PROPS;
  $justifyContent?: TYPE_FLEX_CONTAINER_PROPS;
  $alingItems?: TYPE_FLEX_CONTAINER_PROPS;
  $alingContent?: TYPE_FLEX_CONTAINER_PROPS;
  $order?: number;
  $grow?: number;
  $flex?: number;
  $gap?: number;
  $rowGap?: number;
  $columnGap?: number;
  $basis?: number;
  $wrap?: TYPE_VALUE_PROPS;
  $row?: TYPE_VALUE_PROPS;
  $column?: TYPE_VALUE_PROPS;
  $shrink?: number;
};
