import { Sidebar } from '@/components/sidebar/Sidebar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
};

export default function DashboardLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='grid min-h-screen font-sans antialiased  grid-cols-app'>
      <Sidebar />
      <main className='px-4 pb-12 pt-8'>{children}</main>
    </div>
  );
}
